nohup python3 hyperparameter_search.py --model alexnet > nohup_alexnet.out &
nohup python3 hyperparameter_search.py --model fc1 > nohup_fc1.out &
nohup python3 hyperparameter_search.py --model fc2 > nohup_fc2.out &
nohup python3 hyperparameter_search.py --model resnet34 > nohup_resnet34.out &
nohup python3 hyperparameter_search.py --model resnet50 > nohup_resnet50.out &
nohup python3 hyperparameter_search.py --model resnet101 > nohup_resnet101.out &
nohup python3 hyperparameter_search.py --model GoogLeNet > nohup_GoogLeNet.out &
nohup python3 hyperparameter_search.py --model vgg11 > nohup_vgg11.out &
nohup python3 hyperparameter_search.py --model vgg16 > nohup_vgg16.out &
nohup python3 hyperparameter_search.py --model vgg19 > nohup_vgg19.out &